[package]
name = "rust_zeromq_box"
version = "0.1.0"
edition = "2021"

[dependencies]
zeromq = "0.3.5"
tokio = { version = "1.36.0", features = ["full"] }
signal-hook = "0.3.17"

[[bin]]
name = "message_broker"
[[bin]]
name = "message_client"
[[bin]]
name = "message_server"
