[package]
name = "rust_zeromq_box"
version = "0.1.0"
edition = "2021"

[dependencies]
zeromq = "0.3.5"
tokio = { version = "1.36.0", features = ["full"] }
flatbuffers = "23.5.26"
bytes = "1.5.0"

[build-dependencies]
flatc-rust = "0.2.0"
protoc-rust = "2.28.0"
